# Generated by Django 3.2.4 on 2022-02-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0024_auto_20211107_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sorting',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
